name: End to End Tests

on:
  push:
    branches: [ qarentena-gh-actions ]

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    name: Testes qarentena
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/tests
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: report

